### ISSUE TITLE
add some badges to the Readme file

### ISSUE THREAD

**Issue by Umesh-01** [Learn-For-Cause/Forum-Thread#15]
## Description
add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/83420185/124014601-56bd4880-da01-11eb-8ea0-2e10058b054d.png)

I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

### Work under/as

- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@Ash-exp @dheeraj0802 Should I make these changes??

**Comment by Ash-exp** [comment]
Go ahead and raise a PR and we'll look forward to it
PR description must contain :
`1. A brief of your contribution`
`2. changed file names`
`3. Screenshots of your results`
